### ISSUE TITLE
IWrapsElement Error on Protractor 0.12.0 and Selenium.WebDriver 4.0.0-alpha01

### ISSUE THREAD

**Issue by malpearson** [bbaia/protractor-net#82]
When installing Selenium.WebDriver 4.0.0-alpha01 along with Protractor 0.12.0 I'm getting the following error at compile time:
Error CS7069 Reference to type 'IWrapsElement' claims it is defined in 'WebDriver', but it could not be found.

This error occurs when trying to perform the following commands:
IWebElement webElement = ngWebDriver.FindElement(by);
IWebElement webElement = ngWebElement.FindElement(by);

I did not encounter these errors when using Selenium.WebDriver 3.141.0 along with Protractor 0.12.0, so I'm assuming it must be a Protractor incompatibility with Selenium.WebDriver 4.0.0-alpha01.

Will a new version of Protractor be released soon?

**Comment by malpearson** [comment]
@bbaia could you please remove "using OpenQA.Selenium.Internal;" from Protractor/NgWebElement.cs and Protractor/NgWebDriver.cs and tag a new release for Selenium.WebDriver 4.0.0-alpha01?

Per ﻿v4.0.0a1 in https://github.com/SeleniumHQ/selenium/blob/master/dotnet/CHANGELOG
"Moved IWrapsDriver and IWrapsElement from the OpenQA.Selenium.Internal namespace to the OpenQA.Selenium namespace. This should be a no-op for the vast majority of users, requiring only a recompile of code, given that both of these interfaces feature return types in the base namespace, meaning that users likely already have "using" statements for the root namespace in their source. If errors are encountered, changing the namespace in the code and rebuilding should resolve the error."

Otherwise the code will compile with Protractor 0.12.0 and Selenium.WebDriver 4.0.0-alpha01, but throws the following exceptions at runtime:
System.TypeLoadException : Could not load type 'OpenQA.Selenium.Internal.IWrapsDriver' from assembly 'WebDriver, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null'.

System.TypeLoadException : Could not load type 'OpenQA.Selenium.Internal.IWrapsElement' from assembly 'WebDriver, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null'.

**Comment by Wowo10** [comment]
Got the same issue with Selenium.WebDriver 4.0.0-alpha03 and protractor 0.12.0 will it be released?

**Comment by sdjnaik** [comment]
Facing same issue with Protractor 0.13.0. When can we except fix for this issue?

**Comment by bbaia** [comment]
Prerelease 1.0.0-alpha1 is available on NuGet & GitHub packages.

**Comment by rherlin** [comment]
Can someone help on this issue?

Protractor 1.0.0-beta2
Selenium.WebDriver 4.1.0

Calling **new NgWebDriver((IWebDriver) driver)**; throws

'ExecuteScript' in type 'Protractor.NgWebDriver' from assembly 'Protractor, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.

**Comment by bbaia** [comment]
Protractor 1.0.0 with Selenium.WebDriver 4.1.0 have been released!
